version: "3.9"
services:
  php:
    build: .
    restart: on-failure
    volumes:
      - .:/var/www/html
  nginx:
    image: nginx:1.21.0-alpine
    restart: on-failure
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "54380:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw

volumes:
  postgres_data: